/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomInput {
        "customstyle": string;
        "placeholder": string;
    }
    interface ToggleVisibility {
    }
}
export interface ToggleVisibilityCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLToggleVisibilityElement;
}
declare global {
    interface HTMLCustomInputElement extends Components.CustomInput, HTMLStencilElement {
    }
    var HTMLCustomInputElement: {
        prototype: HTMLCustomInputElement;
        new (): HTMLCustomInputElement;
    };
    interface HTMLToggleVisibilityElement extends Components.ToggleVisibility, HTMLStencilElement {
    }
    var HTMLToggleVisibilityElement: {
        prototype: HTMLToggleVisibilityElement;
        new (): HTMLToggleVisibilityElement;
    };
    interface HTMLElementTagNameMap {
        "custom-input": HTMLCustomInputElement;
        "toggle-visibility": HTMLToggleVisibilityElement;
    }
}
declare namespace LocalJSX {
    interface CustomInput {
        "customstyle"?: string;
        "placeholder"?: string;
    }
    interface ToggleVisibility {
        "onToggleChange"?: (event: ToggleVisibilityCustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "custom-input": CustomInput;
        "toggle-visibility": ToggleVisibility;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-input": LocalJSX.CustomInput & JSXBase.HTMLAttributes<HTMLCustomInputElement>;
            "toggle-visibility": LocalJSX.ToggleVisibility & JSXBase.HTMLAttributes<HTMLToggleVisibilityElement>;
        }
    }
}
